### PR TITLE
suite improvements (bug 1920987)

### PR DESCRIPTION
**Pull request by shtrom**

### CODE REVIEW

**Comment by shtrom** [comment]
@zzzeid this PR is against the `main` branch of suite, and update a few things unrelated to new lando.

**Comment by shtrom** [comment]
Crucially, while it fixes a number of nits, it doesn't fix lando, as I was working on the new version in #59.

**Comment by shtrom** [comment]
@dklawren @cgsheeh you may be able to review this, too.

**Review by dklawren — APPROVED** [review]
This all LGTM but I cannot fully test due to getting a build error with `lando-api.landing-worker` which is not related to these changes.

```
1.256 ERROR: No matching distribution found for celery==4.3.0
------

Dockerfile:45
--------------------
  43 |     COPY requirements.txt /python_requirements.txt
  44 |     RUN pip install pip --upgrade
  45 | >>> RUN pip install --no-cache -r /python_requirements.txt
  46 |     
  47 |     COPY migrations /migrations
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache -r /python_requirements.txt" did not complete successfully: exit code: 1
ERROR: Service 'lando-api.landing-worker' failed to build : Build failed
```

**Comment by shtrom** [comment]
It seems to work for me. I pulled the latest changes on `main` in my local `../lando-api`

**Comment by dklawren** [comment]
> It seems to work for me. I pulled the latest changes on `main` in my local `../lando-api`
> 
> Maybe it was a transient issue? I could also manually install `celery=4.3.0` in a python:3.8 container.

As discussed I was not using an updated checkout of lando-api and once I did that this worked as expected.

**Review by cgsheeh — APPROVED** [review]
LGTM.

**Pull request merged**
